--- #YAML:1.0
name: Class-Trait
version: 0.22
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "An implementation of Traits in Perl"
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
